### ISSUE TITLE
Cannot compile with Xcode 10

### ISSUE THREAD

**Issue by kardeslik** [mattt/Godzippa#17]
Hey there,

The project doesn't compile with Xcode 10 because of `Copy Bundle Resources` steps in different targets causing `Multiple commands produce` error.

What is the reason for copying `Godzippa/Tests/Info.plist` via that steps? Can those steps be removed?

Thanks.

**Comment by mattt** [comment]
Hi @kardeslik. Thanks for the heads-up. Indeed, I believe that step can be removed. I made this change with 0a449b0, which fixes the compilation error you identified. This is now available in version 2.1.0.
